## Pertemuan 3

## Library

In [6]:
import numpy as np
import pandas as pd
import scipy
from scipy.spatial.distance import cityblock, mahalanobis

## Dataset

In [7]:
# dataset pertama untuk perhitungan euclidean distance
P1 = np.array((4, 1))
P2 = np.array((1, 3))

# dataset kedua untuk perhitungan mahalanobis distance
X = np.array([[7.0, 165, 5], [7.4, 160, 5], [7.1, 170, 4], [7.3, 150, 5], [7.2, 160, 3]])

In [8]:
# info dataset 
print(X.shape)
print(X.ndim)
print(X)

(5, 3)
2
[[  7.  165.    5. ]
 [  7.4 160.    5. ]
 [  7.1 170.    4. ]
 [  7.3 150.    5. ]
 [  7.2 160.    3. ]]


## Calculate Distance

## Manhattan Distance

In [9]:
mht_dist = cityblock(P1, P2)
print(mht_dist)

5


## Euclidean Distance

In [10]:
# hitung selisih antara dua vectors
temp = P1 - P2

# gunakan formula euclidean d library numpy
euclid_dist = np.sqrt(np.dot(temp.T, temp))
print(euclid_dist)
# print(np.dot(temp.T, temp))

3.605551275463989


## Mahalanobis Distance

In [11]:
# Hitung kovarians dan inverse kovarians dari dataset
cov = np.cov(X.T)
inv_cov = np.linalg.inv(cov)

# Dua data baru dalam dataset 
x1 = np.array([7.1, 145, 3])
x2 = np.array([6.0, 100, 5])

# Hitung jarak Mahalamobis antara dua titik
mhlnbs_dist = mahalanobis(x1, x2, inv_cov)
print(mhlnbs_dist)

15.370699331286659


#Soal  

* Tentukan mahalanobis distance untuk setiap row yang ada didata ini
* Normalisasi juga hasil mahalanobis distance menggunakan perhitungan p-value 

In [12]:
def mahalanobis(x, data):
  x_min_mean = x - np.mean(data)
  inv_cov = np.linalg.inv(np.cov(data.T))

  return np.dot(np.dot(x_min_mean, inv_cov), x_min_mean.T).diagonal()
  # np.dot(x_min_mean.T, inv_cov)

In [13]:
# Buat Dataset
df = pd.DataFrame({\
    "Diameter (f1)":[7.0, 7.4, 7.1, 7.3, 7.2, 7.1, 6.0],\
    "Berat (f2)":[165, 160, 170, 150, 160, 145, 100],\
    "Tingkat Kemerahan (f3)":[5, 5, 4, 5, 3, 3, 5]\
    })
print(df.iloc[0])

Diameter (f1)               7.0
Berat (f2)                165.0
Tingkat Kemerahan (f3)      5.0
Name: 0, dtype: float64


In [14]:
# Hitung Kovarians dan Inverse-Kovarians
cov_df = np.cov(df.values.T)
cov_df

array([[ 2.18095238e-01,  9.58333333e+00, -1.04761905e-01],
       [ 9.58333333e+00,  5.58333333e+02, -5.00000000e+00],
       [-1.04761905e-01, -5.00000000e+00,  9.04761905e-01]])

In [15]:
df.values[0]

array([  7., 165.,   5.])

In [16]:
mahalanobis(df, df)

array([2.444376  , 1.94047203, 1.99978912, 2.30173528, 1.84568898,
       2.48353228, 4.9844063 ])

In [17]:
# Hitung Jarak Mahalanobis
df_final = df.copy()
df_final["Mahalanobis"] = mahalanobis(df, df)

In [18]:
df_final

Diameter (f1)  Berat (f2)  Tingkat Kemerahan (f3)  Mahalanobis
0            7.0         165                       5     2.444376
1            7.4         160                       5     1.940472
2            7.1         170                       4     1.999789
3            7.3         150                       5     2.301735
4            7.2         160                       3     1.845689
5            7.1         145                       3     2.483532
6            6.0         100                       5     4.984406

In [19]:
from scipy.stats import chi2

In [20]:
df_final['p'] = chi2.sf(df_final['Mahalanobis'], 3)

In [21]:
df_final

Diameter (f1)  Berat (f2)  Tingkat Kemerahan (f3)  Mahalanobis         p
0            7.0         165                       5     2.444376  0.485428
1            7.4         160                       5     1.940472  0.584853
2            7.1         170                       4     1.999789  0.572450
3            7.3         150                       5     2.301735  0.512189
4            7.2         160                       3     1.845689  0.605043
5            7.1         145                       3     2.483532  0.478275
6            6.0         100                       5     4.984406  0.172943